/*
	CRUD  STORED PROC FOR ASSIGNMENTS TABLE 
*/

USE FACULTYDB;
GO


CREATE PROC sp_InsertAssignment
				@TITLE NVARCHAR(150),
				@DESCRIPTION NVARCHAR (MAX),
				@DUEDATETIME DATETIME,
				@FILEPATH NVARCHAR (255),
				@CREATEDBYID INT 
AS 
BEGIN
INSERT INTO ASSIGNMENTS (Title,Description,DueDateTime,FilePath,CreatedById,CreatedAt)
VALUES (@TITLE,@DESCRIPTION,@DUEDATETIME,@FILEPATH,@CREATEDBYID,GETDATE());
END




CREATE PROC sp_GetAssignmentsByFaculty
					@FACULTYID		INT
AS
BEGIN
		SELECT * FROM ASSIGNMENTS WHERE CreatedById = @FACULTYID;
END
GO




CREATE PROC sp_GetAssignmentById
				@ASSIGNMENTID		INT
AS
BEGIN
		SELECT * FROM ASSIGNMENTS WHERE AssignmentId = @ASSIGNMENTID;
END
GO


CREATE PROC sp_UpdateAssignment
					@ASSIGNMENTID	INT,
					@TITLE			NVARCHAR(150),
					@DESCRIPTION		NVARCHAR(MAX),
					@DUEDATETIME		DATETIME,
					@FILEPATH			NVARCHAR(255)
AS
BEGIN
	UPDATE ASSIGNMENTS
	SET			Title = @TITLE,
				Description = @DESCRIPTION,
				DueDateTime = @DUEDATETIME,
				FilePath = @FILEPATH
	WHERE AssignmentId = @ASSIGNMENTID;
END
GO




CREATE PROC sp_DeleteAssignment
					@ASSIGNMENTID	INT
AS
BEGIN
	DELETE FROM ASSIGNMENTS WHERE AssignmentId = @ASSIGNMENTID;
END
GO