/*
	CRUD  STORED PROC FOR SUBMISSIONS TABLE 
*/

USE FACULTYDB;
GO




CREATE PROC sp_InsertSubmission
				@ASSIGNMENTID INT , 
				@STUDENTID	INT,
				@FILEPATH NVARCHAR(255)
AS
BEGIN
INSERT INTO SUBMISSIONS(AssignmentId,StudentId,FilePath,SubmittedAt)
VALUES (@ASSIGNMENTID,@STUDENTID,@FILEPATH,GETDATE());
END



CREATE PROC sp_GetSubmissionByAssignment
							@ASSIGNMENTID		INT
AS
BEGIN
		SELECT * FROM SUBMISSIONS WHERE AssignmentId = @ASSIGNMENTID;
END
GO



CREATE PROC sp_GetSubmissionById
				@SUBMISSIONID	INT
AS
BEGIN
		SELECT * FROM SUBMISSIONS WHERE SubmissionId = @SUBMISSIONID;
END
GO


CREATE PROC sp_UpdateSubmission
					@SUBMISSIONID  INT,
					@FILEPATH		NVARCHAR(255)
AS
BEGIN
		UPDATE SUBMISSIONS
		SET		FilePath = @FILEPATH,
				SubmittedAt = GETDATE()
		WHERE SubmissionId = @SUBMISSIONID;
END
GO




CREATE PROC sp_DeleteSubmission
					@SUBMISSIONID	INT
AS
BEGIN
		DELETE FROM SUBMISSIONS WHERE SubmissionId = @SUBMISSIONID;
END
GO