/*
	CRUD  STORED PROC FOR ASSESSMENT RESULT TABLE 
*/

USE FACULTYDB;
GO


CREATE PROC sp_InsertAssignmentResult 
				@SUBMISSIONID	INT ,
				@CRITERIAID		INT ,
				@SCORE			INT,
				@REMARK		NVARCHAR(255)
AS 
BEGIN
INSERT INTO ASSESSMENTRESULTS (SubmissionId,CriteriaId,Score,Remark)
VALUES (@SUBMISSIONID,@CRITERIAID,@SCORE,@REMARK);
END




CREATE PROC sp_GetResultBySubmission
					@SUBMISSIONID		INT
AS
BEGIN
		SELECT AR.* , C.CriteriaName
		FROM ASSESSMENTRESULTS AR
		INNER JOIN ASSESSMENTCRITERIA C
		ON AR.CriteriaId = C.CriteriaId
		WHERE AR.SubmissionId = @SUBMISSIONID;
END
GO



CREATE PROC sp_GetResultById
					@RESULTID		INT
AS
BEGIN
		SELECT * FROM ASSESSMENTRESULTS WHERE ResultId = @RESULTID;
END
GO




CREATE PROC sp_UpdateAssessmentResult
					@RESULTID	INT,
					@SCORE		INT,
					@REMARK		NVARCHAR(255)
AS
BEGIN
	UPDATE ASSESSMENTRESULTS 
	SET		Score = @SCORE,
			Remark = @REMARK
	WHERE ResultId = @RESULTID;
END
GO



CREATE PROC sp_DeleteAssessmentResult
				@RESULTID		INT
AS
BEGIN
		DELETE FROM ASSESSMENTRESULTS WHERE ResultId = @RESULTID;
END
GO



