CREATE DATABASE FACULTYDB;
GO

USE FACULTYDB;
GO

CREATE TABLE USERS 
(

UserId INT PRIMARY KEY IDENTITY(1,1),
UserName NVARCHAR (100) NOT NULL,
Email NVARCHAR (50) NOT NULL UNIQUE , 
PasswordHash NVARCHAR (255) NOT NULL,
Role NVARCHAR (20) NOT NULL CHECK (Role IN ('Faculty','Student')),
CreatedAt DATETIME DEFAULT GETDATE()

);
GO

CREATE TABLE ASSIGNMENTS
(

AssignmentId INT PRIMARY KEY IDENTITY (1,1),
Title NVARCHAR (150) NOT NULL,
Description NVARCHAR(MAX),
DueDateTime DATETIME NOT NULL,
FilePath NVARCHAR (255),
CreatedById INT NOT NULL,
CreatedAt DATETIME DEFAULT GETDATE(),

CONSTRAINT FK_ASSIGNMENT_USERS FOREIGN KEY (CreatedById) REFERENCES USERS(UserId)


);
GO

CREATE TABLE SUBMISSIONS
(

 SubmissionId INT PRIMARY KEY IDENTITY (1,1),
 AssignmentId INT NOT NULL,
 StudentId INT NOT NULL,
 FilePath NVARCHAR (255),
 SubmittedAt DATETIME DEFAULT GETDATE(),

 CONSTRAINT FK_SUBMISSION_ASSIGNMENTS FOREIGN KEY (AssignmentId) REFERENCES ASSIGNMENTS(AssignmentId),
 CONSTRAINT FK_SUBMISSION_STUDENT FOREIGN KEY (StudentId) REFERENCES USERS(UserId)

);
GO

CREATE TABLE ASSESSMENTCRITERIA
(

CriteriaId INT PRIMARY KEY IDENTITY (1,1),
AssignmentId INT NOT NULL,
CriteriaName NVARCHAR (100) NOT NULL,
MaxScore INT NOT NULL CHECK (MaxScore > 0),

CONSTRAINT FK_CRITERIA_ASSIGNMENT FOREIGN KEY (AssignmentId) REFERENCES ASSIGNMENTS (AssignmentId)

);
GO

CREATE TABLE ASSESSMENTRESULTS
(

ResultId INT PRIMARY KEY IDENTITY (1,1),
SubmissionId INT NOT NULL,
CriteriaId INT NOT NULL,
Score INT NOT NULL CHECK (Score >=0),
Remark NVARCHAR (255),

CONSTRAINT FK_RESULTS_SUBMISSION FOREIGN KEY (SubmissionId) REFERENCES SUBMISSIONS (SubmissionId),
CONSTRAINT FK_RESULTS_CRITERIA FOREIGN KEY (CriteriaId) REFERENCES ASSESSMENTCRITERIA(CriteriaId)

);
GO