USE FACULTYDB;
GO 


CREATE PROC sp_InsertUser
				@Name NVARCHAR(100),
				@Email NVARCHAR(100),
				@PasswordHash NVARCHAR (255),
				@Role NVARCHAR (20)
AS
BEGIN
INSERT INTO USERS (UserName,Email,PasswordHash,Role,CreatedAt)
VALUES (@Name,@Email,@PasswordHash,@Role,GETDATE());
END



CREATE PROC sp_InsertAssignment
				@TITLE NVARCHAR(150),
				@DESCRIPTION NVARCHAR (MAX),
				@DUEDATETIME DATETIME,
				@FILEPATH NVARCHAR (255),
				@CREATEDBYID INT 
AS 
BEGIN
INSERT INTO ASSIGNMENTS (Title,Description,DueDateTime,FilePath,CreatedById,CreatedAt)
VALUES (@TITLE,@DESCRIPTION,@DUEDATETIME,@FILEPATH,@CREATEDBYID,GETDATE());
END

CREATE PROC sp_InsertSubmission
				@ASSIGNMENTID INT , 
				@STUDENTID	INT,
				@FILEPATH NVARCHAR(255)
AS
BEGIN
INSERT INTO SUBMISSIONS(AssignmentId,StudentId,FilePath,SubmittedAt)
VALUES (@ASSIGNMENTID,@STUDENTID,@FILEPATH,GETDATE());
END

CREATE PROC sp_InsertAssignmentCriteria
				@ASSIGNMENTID INT ,
				@CRITERIANAME NVARCHAR(100),
				@MAXSCORE INT 
AS
BEGIN
INSERT INTO ASSESSMENTCRITERIA (AssignmentId,CriteriaName,MaxScore)
VALUES (@ASSIGNMENTID,@CRITERIANAME,@MAXSCORE);
END


CREATE PROC sp_InsertAssignmentResult 
				@SUBMISSIONID	INT ,
				@CRITERIAID		INT ,
				@SCORE			INT,
				@REMARK		NVARCHAR(255)
AS 
BEGIN
INSERT INTO ASSESSMENTRESULTS (SubmissionId,CriteriaId,Score,Remark)
VALUES (@SUBMISSIONID,@CRITERIAID,@SCORE,@REMARK);
END
